# Generated by Django 2.0.8 on 2021-05-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prix', models.FloatField(max_length=250)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
    ]
